# See http://www.appveyor.com/docs/appveyor-yml for many more options
os: Unstable

# Init variables for publishing to PowerShell Gallery or GitHub
environment:
  ModuleName: $(APPVEYOR_PROJECT_NAME) # Hard code if you really need to...
  Tags: 'SQL,SQLite,Database,Query' #comma separated list, e.g. 'tag1,tag2,tag3'
  ReleaseNotes: 'Added UNC support'
  LicenseUri: 'https://raw.githubusercontent.com/RamblingCookieMonster/PSSQLite/master/LICENSE'
  ProjectUri: 'http://ramblingcookiemonster.github.io/SQLite-and-PowerShell/'
  GitHubRelease: $(APPVEYOR_PROJECT_NAME)-v1.0.1 # TODO: extract version from PSD1...
  NugetApiKey: # Add your API key to AppVeyor, paste the encrypted bit here
    secure: oqMFzG8F65K5l572V7VzlZIWU7xnSYDLtSXECJAAURrXe8M2+BAp9vHLT+1h1lR0

build: false

#Beware the infinite rebuild bug. Woke up to 84 new releases!
#skip_tags: true

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*/

# PS2 compat
install:
  - cinst pester -y

# Package things up.
#build_script:
#  - 7z a %ModuleName%.zip %ModuleName%\

# Test with native PS and PS version 2. Upload test results
test_script:
  # Comment out this line to avoid testing in PSv2
  - ps: . .\Tests\appveyor.pester.ps1 -ConfigurePester
  - ps: powershell.exe -version 2.0 -executionpolicy bypass -noprofile -file .\Tests\appveyor.pester.ps1 -Test
  - ps: . .\Tests\appveyor.pester.ps1 -Test -Finalize

# zipped package for delivery
#artifacts:
#  - path: $(ModuleName).zip

# Duct tape, until this is implemented:
#    https://github.com/appveyor/ci/issues/128
#deploy_script:
#  - ps: . .\Tests\appveyor.pester.ps1 -Deploy
